language: node_js

node_js:
   - 10

arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - grunt-cli
       - grunt
       - npm 
       - wget 
